apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secrets
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt_secret: {{ .Values.secrets.jwt_secret | quote }}
  {{- if .Values.secrets.admin_api_key }}
  admin_api_key: {{ .Values.secrets.admin_api_key | quote }}
  {{- end }}
  {{- if .Values.secrets.partner_api_key }}
  partner_api_key: {{ .Values.secrets.partner_api_key | quote }}
  {{- end }}

{{- if and .Values.config.tls.enabled (not .Values.tls.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-tls
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
  {{- if .Values.tls.ca }}
  ca.crt: {{ .Values.tls.ca | b64enc }}
  {{- end }}
{{- end }}
